name: bitcoin-backtest
services:
- name: web
  source_dir: /
  github:
    repo: jyothirmai0564/bitcoin_backtest  # Your GitHub repo
    branch: main
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  routes:
  - path: /
  run_command: python optimized_backtest.py  # Your main file