name: bitcoin-trading-system
services:
- name: web
  github:
    repo: jyothirmai0564/bitcoin-backtest
    branch: main
    deploy_on_push: true
  
  source_dir: /
  environment_slug: python-3.13
  
  run_command: uvicorn main:app --host 0.0.0.0 --port 8080
  
  build_command: |
    pip install -r requirements.txt
    
  
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  
  health_check:
    http_path: /health
    initial_delay_seconds: 60  # Give more time for initial backtest